### ISSUE TITLE
项目引用了com.alibaba:fastjson@1.2.66等85个开源组件，存在5个严重漏洞，建议升级

### ISSUE THREAD

**Issue by AbbyWoo** [wangsrGit119/suc-chat-bandend#10]
大佬，我看你这个项目引用了com.alibaba:fastjson@1.2.66等85个开源组件，存在5个严重漏洞，建议你升级下。
```
漏洞标题：Fastjson <=1.2.68 远程代码执行漏洞
漏洞编号：
漏洞描述：
Fastjson 是Java语言实现的快速JSON解析和生成器，在<=1.2.68的版本中攻击者可通过精心构造的JSON请求，远程执行恶意代码。
漏洞原因：
Fastjson采用黑白名单的方法来防御反序列化漏洞，导致当黑客不断发掘新的反序列化Gadgets类时，发现在autoType关闭的情况下仍然可能可以绕过黑白名单防御机制，造成远程命令执行漏洞。
国家漏洞库信息：https://www.cnvd.org.cn/flaw/show/CNVD-2020-30827
漏洞级别：严重
影响范围：(-∞, 1.2.69)
最小修复版本：sec10
引入路径：
cn.wangsr.chat:suc-chat-backend:0.0.1-SNAPSHOT->com.alibaba:fastjson@1.2.66
```
其它还有4个严重漏洞 ，信息有点多我就不贴了，你自己看下完整报告：https://www.murphysec.com/j?p=ab3023

**Comment by wangsrGit119** [comment]
自行处理即可，仓库里面的暂时不用管



---原始邮件---
发件人: "Abby ***@***.***&gt;
发送时间: 2022年1月9日(周日) 下午2:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wangsrGit119/suc-chat-bandend] ***@***.***等85个开源组件，存在5个严重漏洞，建议升级 (Issue #10)




 
***@***.***等85个开源组件，存在5个严重漏洞，建议你升级下。
 漏洞标题：Fastjson <=1.2.68 远程代码执行漏洞 漏洞编号： 漏洞描述： Fastjson 是Java语言实现的快速JSON解析和生成器，在<=1.2.68的版本中攻击者可通过精心构造的JSON请求，远程执行恶意代码。 漏洞原因： Fastjson采用黑白名单的方法来防御反序列化漏洞，导致当黑客不断发掘新的反序列化Gadgets类时，发现在autoType关闭的情况下仍然可能可以绕过黑白名单防御机制，造成远程命令执行漏洞。 国家漏洞库信息：https://www.cnvd.org.cn/flaw/show/CNVD-2020-30827 漏洞级别：严重 影响范围：(-∞, 1.2.69) 最小修复版本：sec10 引入路径： ***@***.***  
其它还有4个严重漏洞 ，信息有点多我就不贴了，你自己看下完整报告：https://www.murphysec.com/j?p=ab3023
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
