### ISSUE TITLE
前端

### ISSUE THREAD

**Issue by sktxxx** [wangsrGit119/suc-chat-bandend#7]
没有页面？

**Comment by wangsrGit119** [comment]
肯定有的撒 ，和这个仓库并排的首页；
[https://github.com/wangsrGit119/suc-love-chat](https://github.com/wangsrGit119/suc-love-chat)

**Comment by wangsrGit119** [comment]
呀昨天没艾特到你，@sktxxx 看上面链接

**Comment by sktxxx** [comment]
> 呀昨天没艾特到你，@sktxxx 看上面链接

好的谢谢，其实昨天我已经看到了，我的邮箱关联了GitHub。
